version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./application:/var/www/html
    depends_on:
      - postgres
      - redis

    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: notifyuser
      DB_USERNAME: dervis
      DB_PASSWORD: dervis123
      REDIS_HOST: redis
      REDIS_PORT: 6379

    expose:
    - 9000

  nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - ./application:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  postgres:
    image: postgres:15
    container_name: laravel_postgres
    restart: always
    environment:
      POSTGRES_DB: notifyuser
      POSTGRES_USER: dervis
      POSTGRES_PASSWORD: dervis123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: laravel_redis
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    container_name: laravel_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dervis@admin.com
      PGADMIN_DEFAULT_PASSWORD: dervis123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pgdata:
  pgadmin_data:
